isodur/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import url, i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from isodur_app import views

urlpatterns = [
    url(r'^i18n', include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns(
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^company/$', views.CompanyView.as_view(), name='company'),
    url(r'^product-1/$', views.ProductListView.as_view(), name='product1'),
    url(r'^product-2/$', views.Product2.as_view(), name='product2'),
    url(r'^product-3/$', views.Product3.as_view(), name='product3'),
    url(r'^steps/$', views.Steps.as_view(), name='steps'),
    url(r'^projects/$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^admin/',  include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^video/$', views.ProjectVideoView.as_view(), name='project_video'),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

isodur_app/models.py
from django.db import models


class Product1(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200)
    products_photo = models.ImageField(upload_to='products_photo', null=True, blank=True)

    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200)
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProjectPhoto(models.Model):
    project = models.ForeignKey(Project, null=True, blank=True)
    project_photo = models.ImageField(upload_to='project_photo', null=True, blank=True)
    add_to_slider = models.BooleanField(default=False)


class Partner(models.Model):
    title = models.CharField(max_length=100)
    partner_image = models.ImageField(upload_to='partners', null=True, blank=True)

    def __str__(self):
        return self.title

isodur_app/forms.py
from django import forms
from captcha.fields import CaptchaField


class ContactForm(forms.Form):
    name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'First and last name'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email Address'}))
    marketing = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Marketing'}))
    captcha = CaptchaField()
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Message'}))

isodur_app/views.py
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView

from .forms import ContactForm
from .models import Project, Partner, Product1


class HomeView(TemplateView):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        from django.utils.translation import get_language_from_request, get_language_from_path, activate
        activate(get_language_from_path(request.path))
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['partners'] = Partner.objects.all()
        return context


class CompanyView(TemplateView):
    template_name = 'company.html'


class ProductListView(ListView):
    model = Product1
    context_object_name = 'products'
    template_name = 'products/product_1.html'


class Product2(TemplateView):
    template_name = 'products/product_2.html'


class Product3(TemplateView):
    template_name = 'products/product_3.html'


class Steps(TemplateView):
    template_name = 'steps.html'


class ProjectVideoView(TemplateView):
    template_name = 'project_video.html'


class ProjectListView(ListView):
    model = Project
    context_object_name = 'projects'
    template_name = 'project_list.html'


def contacts(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            sender = form.cleaned_data['email']
            marketing = form.cleaned_data['marketing']
            message = 'From: {}\n{}'.format(name, form.cleaned_data['message'])

            recipients = [settings.EMAIL_HOST_USER]
            try:
                send_mail(marketing, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return render(request, 'contacts_thanks.html')

        else:
            context = {'form': form}
            return render(request, 'contacts.html', context)

    form = ContactForm()

    return render(request, 'contacts.html', {'form': form})

templates/base.html
{% load lang_tags staticfiles i18n %}
<!DOCTYPE html>
<html>
<head>
    {% block title %}
        <title></title>
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="{% static 'favicon.ico' %}" rel="icon" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=BioRhyme:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link href="{% static 'owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'animate.css' %}" rel="stylesheet">
</head>

<body class="body-wrapper">
{% if request.path == '/' or request.path == '/en/' %}
    {% include 'navbar.html' %}
{% else %}
    {% include 'white-header.html' %}
{% endif %}
<main class="main-wrapper">
    {% block content %}

    {% endblock content %}
</main>
{% include 'footer.html' %}
{#{% ifequal request.path '/' %}#}
{#{% include 'white_footer.html' %}#}
{#{% else %}#}
{#{% include 'footer.html' %}#}
{#{% endifequal %}#}
{% include 'js.html' %}
<script src="{% static 'app.js' %}" type="text/javascript"></script>
</body>
</html>

templates/company.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}
    <div class="company-wrapper">
        <div class="line_title">
            <h4 class="animated fadeIn"><cite>« Economie </cite><span><cite>d’énergie »</cite></span></h4>
            <h4 class="animated fadeIn"><cite>« Solidité </cite><span><cite>antisismique »</cite></span></h4>
        </div>
        <div class="brand-logo-box_company">
            <img width="100%" height="70%" src="{% static 'header/isodurhouse.png' %}" alt="logo_isodur">
        </div>
        <h4 class="bottom_cite animated fadeIn"><cite>« Rapidité de </cite><span><cite>construction »</cite></span></h4>
        <div class="company-description">
            <p>
                {% blocktrans %}
                    'ISODUR HOUSE est une societe fondee en l'an 2009 la sodete est engagee clans le developpement de la
                    construction solide, pratique et durable du gros euvre, respectueux de l'environnement, ISODUR HOU
                    SE Beneficie d'une experience de longue date, et a initie son expansion sur le marche africain de
                    construction par sa presence sur le marche marocain.'
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    ISODUR HOU SE presente sa troisieme version du bloc de coffrage isolant, cree pour fournir un
                    service unique a ceux qui veulent construire en utilisant des systemes de construction de qualite
                    superieure. Qu1I s'agisse de logements ou d'unites industrielles, d'ecoles OU d'hotels ...
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    Nous avons les competences pour conseiller, planifier, approvisionner, construire et apporter de
                    !'assistance technique au stade de la planification, et pour la fourniture de materiaux divers et de
                    la main-d'oeuvre spedalisee.
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    Si la reduction des coats et !'amelioration de la qualite sont vos objectifs, entrez en contact avec
                    ISO DUR HOUSE. La performance a votre service et a celui de l'environnement.
                {% endblocktrans %}
            </p>
            <cite>
                {% blocktrans %}« La société est engagée dans le développement de la
                    construction solide,
                {% endblocktrans %}
                <br>
                {% trans 'pratique et durable, respectueux de l’environnement.' %} »
                <br>
                <span class="author_quote">{% trans '(Le President de la societe)' %}</span>
            </cite>
            <div class="feedback_text_block_company">
                <h3 class="why-iso flex_comp">
                    <svg class="marg-svg" width="25px" height="25px" fill="#69247c" id="Layer_1" style="enable-background:new 0 0 64 64;" version="1.1" viewBox="0 0 64 64" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><style type="text/css">
	.st0 {
        fill: #69247c;
    }
</style><g><g id="Icon-Question" transform="translate(178.000000, 278.000000)"><path class="st0" d="M-145.9-222c-13.2,0-23.9-10.7-23.9-23.9s10.7-23.9,23.9-23.9c13.2,0,23.9,10.7,23.9,23.9     S-132.7-222-145.9-222L-145.9-222z M-145.9-267.2c-11.7,0-21.3,9.6-21.3,21.3c0,11.7,9.6,21.3,21.3,21.3     c11.7,0,21.3-9.6,21.3-21.3C-124.6-257.7-134.2-267.2-145.9-267.2L-145.9-267.2z" id="Fill-47"/><path class="st0" d="M-153.3-253.5c0.4-1.1,0.9-2,1.6-2.7c0.7-0.7,1.6-1.3,2.6-1.7c1-0.4,2.2-0.6,3.5-0.6     c1,0,2,0.2,2.9,0.5c0.9,0.3,1.7,0.8,2.4,1.3s1.2,1.3,1.6,2.1c0.4,0.8,0.6,1.8,0.6,2.9c0,1.4-0.3,2.5-0.9,3.5s-1.4,1.9-2.3,2.8     c-0.8,0.8-1.4,1.4-1.8,1.8c-0.5,0.4-0.8,0.9-1,1.3s-0.4,0.9-0.4,1.5c-0.1,0.6-0.1,1-0.1,2.1h-2.3c0-1.1,0-1.6,0.2-2.3     c0.1-0.8,0.4-1.4,0.7-2.1c0.3-0.6,0.8-1.2,1.3-1.8c0.6-0.6,1.2-1.2,2-1.9c0.7-0.6,1.3-1.3,1.7-2.1c0.5-0.8,0.7-1.7,0.7-2.6     c0-0.7-0.1-1.4-0.4-2c-0.3-0.6-0.7-1.1-1.1-1.6s-1-0.8-1.7-1c-0.6-0.2-1.3-0.4-2-0.4c-1,0-1.9,0.2-2.6,0.5     c-0.8,0.3-1.4,0.8-1.9,1.4c-0.5,0.6-0.9,1.3-1.1,2.1c-0.2,0.8-0.4,1.5-0.3,2.4h-2.3C-153.8-251.5-153.7-252.4-153.3-253.5     L-153.3-253.5z M-147.3-236h2.8v2.8h-2.8V-236z" id="Fill-48"/></g></g></svg>
                    {% blocktrans %}
                        POURQUOI CHOISIR
                    {% endblocktrans %}
                    <span class="purple">{% trans 'ISODUR' %}</span>
                </h3>
                <p class="center-company-text">{% trans 'LE PRINCIPE EST SIMPLE' %}</p>
                <p>Les coffrages isolés pour béton ISODUR fournissent de nombreux avantages supérieurs
                    lors de la construction d'une structure. Les coffrages ISODUR se composent de deux
                    panneaux de polystyrène expansé (PSE) d'une épaisseur de 5 cm dans chaque
                    panneau.</p>
                <p>
                    {% blocktrans %}
                        Les coffrages ISODUR sont empilés, armés avec de l'acier et remplis de béton, ce qui
                        complète l'enveloppe du bâtiment de votre structure résidentielle en une seule étape de
                        construction.
                    {% endblocktrans %}
                </p>
                <p>
                    {% blocktrans %}
                        Les coffrages ISODUR sont offerts en un éventail de formes et de dimensions de façon
                        à convenir à tous les types d'exigences et de conceptions de construction. ISODUR
                        offre également un éventail de produits accessoires qui complètent notre gamme de
                        produits de coffrage isolé pour béton.
                        Voir les gammes de produits
                    {% endblocktrans %}
                </p>
                <p class="center-company-text">{% trans 'INNOVATION' %}</p>
                <p>{% trans 'Les coffrages isolés pour béton ISODUR fournissent de nombreux avantages lors de la construction.' %}</p>
                <p>
                    {% blocktrans %}
                        La polyvalence et la facilité d'installation des coffrages isolés pour béton ISODUR sont
                        sans pareil avec nos caractéristiques de coffrage novatrices qui fournissent une
                        technologie brevetée que seule la Corporation ISODUR peut vous offrir.
                    {% endblocktrans %}
                </p>
                <p class="center-company-text">{% trans 'ÉTAPES DE CONSTRUCTION 6 EN 1' %}</p>
                <p>
                    {% blocktrans %}
                        Regrouper six éléments muraux en un seul produit élimine des étapes de construction
                        coûteuses et permet de bâtir le projet de construction avec une plus grande rapidité et
                        efficacité.
                    {% endblocktrans %}
                </p>
                <h3 class="why-iso bottom_text_company flex_comp">
                    <svg class="marg-svg" width="25px" height="25px" id="Layer_1" style="enable-background:new 0 0 64 64;" version="1.1" viewBox="0 0 64 64" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><style type="text/css">
	.st0 {
        fill: #69247c;
    }
</style><g><g id="Icon-Question" transform="translate(178.000000, 278.000000)"><path class="st0" d="M-145.9-222c-13.2,0-23.9-10.7-23.9-23.9s10.7-23.9,23.9-23.9c13.2,0,23.9,10.7,23.9,23.9     S-132.7-222-145.9-222L-145.9-222z M-145.9-267.2c-11.7,0-21.3,9.6-21.3,21.3c0,11.7,9.6,21.3,21.3,21.3     c11.7,0,21.3-9.6,21.3-21.3C-124.6-257.7-134.2-267.2-145.9-267.2L-145.9-267.2z" id="Fill-47"/><path class="st0" d="M-153.3-253.5c0.4-1.1,0.9-2,1.6-2.7c0.7-0.7,1.6-1.3,2.6-1.7c1-0.4,2.2-0.6,3.5-0.6     c1,0,2,0.2,2.9,0.5c0.9,0.3,1.7,0.8,2.4,1.3s1.2,1.3,1.6,2.1c0.4,0.8,0.6,1.8,0.6,2.9c0,1.4-0.3,2.5-0.9,3.5s-1.4,1.9-2.3,2.8     c-0.8,0.8-1.4,1.4-1.8,1.8c-0.5,0.4-0.8,0.9-1,1.3s-0.4,0.9-0.4,1.5c-0.1,0.6-0.1,1-0.1,2.1h-2.3c0-1.1,0-1.6,0.2-2.3     c0.1-0.8,0.4-1.4,0.7-2.1c0.3-0.6,0.8-1.2,1.3-1.8c0.6-0.6,1.2-1.2,2-1.9c0.7-0.6,1.3-1.3,1.7-2.1c0.5-0.8,0.7-1.7,0.7-2.6     c0-0.7-0.1-1.4-0.4-2c-0.3-0.6-0.7-1.1-1.1-1.6s-1-0.8-1.7-1c-0.6-0.2-1.3-0.4-2-0.4c-1,0-1.9,0.2-2.6,0.5     c-0.8,0.3-1.4,0.8-1.9,1.4c-0.5,0.6-0.9,1.3-1.1,2.1c-0.2,0.8-0.4,1.5-0.3,2.4h-2.3C-153.8-251.5-153.7-252.4-153.3-253.5     L-153.3-253.5z M-147.3-236h2.8v2.8h-2.8V-236z" id="Fill-48"/></g></g></svg>
                    {% blocktrans %}
                        À QUOI VOUS POUVEZ VOUS ATTENDRE DE
                    {% endblocktrans %}
                    <span class="purple">{% trans 'ISODUR' %}</span>
                </h3>
                <p>
                    {% blocktrans %}
                        ISODUR possède une industrie 100% locale et un vaste réseau de distributeurs
                        autorisés pouvant vous aider du concept à la réalisation de l'installation avec un
                        installateur formé par ISODUR.
                    {% endblocktrans %}
                </p>
                <p>
                    {% blocktrans %}
                        ISODUR se targue de vous fournir le meilleur soutien d'entreprises solides et de bonne
                        réputation au sein de vos régions géographiques locales pour représenter ses produits.
                        Installer le système de coffrage isolé pour béton -ISODUR réduit de façon considérable
                        les coûts de main-d'œuvre et de transport pour les installations typiques. Les coffrages
                        isolés pour béton - ISODUR sont faciles à manipuler, entreposer et installer.
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    </div>

{% endblock content %}

templates/contacts.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}

    <div id="top_contact" class="contacts-wrapper">
        <div class="contacts-title">
            <img class="image-contact" src="{% static 'contact/top_image.png' %}" alt="contact">
            <p class="first-block_text">
                {% blocktrans %}
                    <span>ISODUR HOUSE</span> et t’une industrie locale de matériaux de construction
                    innovants valorisant pleinement les compétences nationales capable
                    d’accompagner et de soutenir les projets nationaux pour le développement de
                    l’habitat écologique et moderne en positionnant le Maroc en tant que
                    fournisseur majeur de matériaux de construction aussi bien au niveau national
                    qu’international, y compris les pays du continent africains.
                {% endblocktrans %}
            </p>
            <h1>{% trans 'NOTRE SERVICE ASSISTANCE ISODUR HOUSE' %}</h1>
            <p class="title_top_text"><span>{% trans 'Réussir son gros œuvre en toute sérénité :' %}</span></p>
            <p>
                {% blocktrans %}
                    La société ISODUR HOUSE, offre à l’ensemble de ses clients une
                    Formation à l’utilisation des blocs coffrant.
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    Cette formation initiale est dispensée au siège ISODUR HOUSE à La zone
                    industrielle Ain Atiq région de Rabat, sur demande comme elle peut se faire
                    directement sur votre chantier selon conditions.
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    Nous invitons les entrepreneurs, architectes, ingénieurs et professionnels de la
                    conception à participer pour en apprendre davantage sur les avantages de la
                    construction avec ISODUR HOUSE.
                {% endblocktrans %}
            </p>
            <div class="block_list">
                <div>
                    <p class="list-title">{% trans 'FORMATION À L’USINE ISODUR HOUSE' %}</p>
                    <ul>
                        <li>{% trans 'Gestion d’un projet de construction' %}</li>
                        <li>{% trans 'Règles et accessoires indispensables' %}</li>
                        <li>{% trans 'Méthodologie de montage' %}</li>
                        <li>{% trans 'Mise en place des étais' %}</li>
                        <li>{% trans 'Conseils pour le coulage du béton' %}</li>
                        <li>{% trans 'Préconisations des méthodes de revêtements' %}</li>
                        <li>{% trans 'Conseils sur les produits compatibles HQE, BBC et passifs' %}</li>
                        <li>{% trans 'Certification ISODUR HOUSE' %}</li>
                    </ul>
                </div>
                <div>
                    <p class="list-title">{% trans 'AVANTAGES DE LA FORMATION' %}</p>
                    <ul>
                        <li>{% trans 'Une formation et une assistance dédiées' %}</li>
                        <li>{% trans 'Un démarrage de chantier en toute confiance' %}</li>
                        <li>{% trans 'Un gain en temps et en efficacité considérable' %}</li>
                        <li>{% trans 'Un montage rapide' %}</li>
                        <li>{% trans 'Un temps libre préservé pour le second œuvre' %}</li>
                        <li>{% trans 'Un délai de réalisation réduit' %}</li>
                        <li>{% trans 'Un budget épargné' %}</li>
                    </ul>
                </div>
            </div>
            <p style="text-align: center; margin-bottom: 50px;">
                {% blocktrans %}
                    'Vous voulez vous inscrire à la formation ? Merci de remplir ce
                    formulaire, nous prendrons contact avec vous le plus rapidement
                    possible.'
                {% endblocktrans %}
            </p>
        </div>
        <form class="form-wrapper" id="i_form" method="post">{% csrf_token %}
            <div class="sec_1">
                <input id="id_name" maxlength="20" name="name" type="text" placeholder="first and last name"
                       autofocus>
                <input id="id_email" name="email" maxlength="50" placeholder="Email Address" type="email">
                <input id="id_marketing" maxlength="50" name="marketing" placeholder="Marketing" type="text">
                <div class="box-captcha">
                    {{ form.captcha }}
                    {{ form.errors.captcha }}
                </div>
            </div>
            <div class="sec_2">
                <textarea cols="40" id="id_message" name="message" placeholder="Message" maxlength="500" rows="10"
                          type="text"></textarea>
                <input class="submit-btn" type="submit" value="{% trans 'Send Message' %}"/>
            </div>
        </form>
    </div>

{% endblock content %}

templates/contacts_thanks.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}
    <div class="success-message">
        <svg viewBox="0 0 76 76" class="success-message__icon icon-checkmark">
            <circle cx="38" cy="38" r="36"/>
            <path fill="none" stroke="#FFFFFF" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"
                  stroke-miterlimit="10" d="M17.7,40.9l10.9,10.9l28.7-28.7"/>
        </svg>
        <h1 class="success-message__title">{% trans 'Message Received' %}</h1>
        <div class="success-message__content">
            <a href="{% url 'home' %}">{% trans 'Go back to main page' %}</a>
        </div>
    </div>
{% endblock content %}

templates/footer.html
{% load staticfiles lang_tags i18n %}

<footer class="footer-decoration_white">
    <div class="footer-actions-wrapper_white">
        <div class="footer-contact-wrapper_white">
            <div class="social-box footer-soc-box">
                <span class="phone footer-cl_white"> <span class="phone-ic"></span>+212 5 37 74 99 91</span>
                <span>|</span>
                <span class="phone footer-cl_white"> <span
                        class="phone-ic"></span>Zone Industrielle Ain Atiq Rabat Maroc</span>
                <div class="social-icons">
                    <a class="social-ic-common" title="facebook"><img src="{% static 'header/facebook.png' %}"
                                                                      alt="facebook"></a>
                    <a class="social-ic-common" title="instagram"><img src="{% static 'header/instagram.png' %}"
                                                                       alt="instagram"></a>
                    <a class="social-ic-common" title="youtube"><img src="{% static 'header/youtube.png' %}"
                                                                     alt="youtube"></a>
                    <a class="social-ic-common" title="linkedin"><img src="{% static 'header/linked.png' %}"
                                                                      alt="linked"></a>
                </div>
            </div>
        </div>
        <div class="footer-language-wrapper_white">
            {% get_available_languages as LANGUAGES %}
            {% for language_code, language_name in LANGUAGES %}
                <a href="{% change_lang language_code %}">{{ language_name }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="footer-copy-info_white">&copy; 2017 Saks Holly Do * CA Transparency in Supply Chains Act</div>
</footer>

templates/project_list.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}
    <div class="projects-wrapper">
        <div class="projects-title">
            <h4>Projet réaliser dans le monde <span>par les blocs de coffrages</span></h4>
            <p>
                {% blocktrans %}
                    ISODUR HOUSE présente sa troisième version du bloc de coffrage isolant, créé pour
                    fournir un service unique à ceux qui veulent construire en utilisant des systèmes de
                    construction de qualité supérieure. Qu’il s’agisse de logements ou d’unités industrielles,
                    d’écoles ou d’hôtels ...
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    Nous avons les compétences pour conseiller, planifier, approvisionner, construire et
                    apporter de l’assistance technique au stade de la planification, et pour la fourniture de
                    matériaux divers et de la main-d’oeuvre spécialisée.
                {% endblocktrans %}
            </p>
            <p>
                {% blocktrans %}
                    Si la réduction des coûts et l’amélioration de la qualité sont vos objectifs, entrez en
                    contact avec ISODUR HOUSE. La performance à votre service et à celui de
                    l’environnement.
                {% endblocktrans %}
            </p>
            <h6>{% trans 'AVEC ISODUR ON PEUT CONSTRUIRE N’IMPORTE QUEL ARCHITECTURE' %}</h6>
            <ul>
                <li>{% trans 'APPARTEMENTS' %}</li>
                <li>{% trans 'VILLAS' %}</li>
                <li>{% trans 'LOGEMENT SOCIAL' %}</li>
                <li>{% trans 'CONSTRUCTION INDUSTRIELLE' %}</li>
                <li>{% trans 'BATIMENT AGRICOLE OU HANGAR' %}</li>
                <li>{% trans 'HOPITAUX ET ECOLES' %}</li>
                <li>{% trans 'HOPITAUX ET ECOLES' %}</li>
                <li>{% trans 'PROJET TOURISTIQUE COMMERCIALE ET MALL' %}</li>
                <li>{% trans 'LES SOUS-SOL ET PISCINES' %}</li>
            </ul>
        </div>
        <div class="projects-items-wrapper">
            {% for project in projects %}
                {% for item in project.projectphoto_set.all %}
                    <div class="item">
                    <a href='{{ project.get_absolute_url }}'>
                        <img src="{{ item.project_photo.url }}" width="100%" height="100%"/><br>
                    </a>
                {% endfor %}
            <div class="insidelay animated fadeIn">
                <div class="inside_block">
                    <h3 class="title-project">{{ project.title }}</h3>
                </div>
            </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <span id="scrollToTop"><img src="{% static 'arrow_up.svg' %}" alt="arrow_up"></span>

{% endblock content %}